/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClickeableCard: typeof import('./src/components/bills/ClickeableCard.vue')['default']
    CommonButton: typeof import('./src/components/commons/CommonButton.vue')['default']
    CommonModal: typeof import('./src/components/commons/CommonModal.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Label: typeof import('radix-vue')['Label']
    NavigationBar: typeof import('./src/components/commons/NavigationBar.vue')['default']
    PaymentsList: typeof import('./src/components/bills/PaymentsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
